language: java
jdk:
  - oraclejdk8
install: gradle setupCIWorkspace build
before_install:
  - chmod +x mirror.sh
  - sh mirror.sh
deploy:
- provider: pages
  skip_cleanup: true
  local_dir: build/libs/
  github_token: $GIT_TOKEN
  repo: RoccoDev/Beezig-Deploy
  target_branch: BeezigLaby-$TRAVIS_BRANCH
  on:
    all_branches: true
    tags: false