language: java
jdk:
  - openjdk8
install: ./gradlew setupCIWorkspace build
before_install:
  - chmod +x mirror.sh
  - chmod +x gradlew
after_success:
  - bash mirror.sh
deploy:
- provider: pages
  skip_cleanup: true
  local_dir: build/libs/
  github_token: $GIT_TOKEN
  repo: RoccoDev/Beezig-Deploy
  target_branch: BeezigLaby-$TRAVIS_BRANCH
  on:
    all_branches: true
    tags: false